---
- name: restart bind9
  systemd:
    name: named
    state: restarted
  become: true

- name: reload bind9
  systemd:
    name: named
    state: reloaded
  become: true

- name: daemon-reload
  systemd:
    daemon_reload: true
  become: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  become: true
