---
# ============================================================
#  tasks/service.yml
#  Habilitar y arrancar el servicio Kea DHCPv4
# ============================================================

- name: Habilitar y arrancar isc-kea-dhcp4-server
  ansible.builtin.systemd:
    name: "{{ kea_service }}"
    state: started
    enabled: true
    daemon_reload: true
