- name: Puerto Radio Enlace
  ansible.netcommon.cli_config:
    parents: interface gigabitethernet 1/1/1
    lines:
      - description Radio_Link_900MHz
      - switchport mode access
      - switchport access vlan 10

- name: Puerto Raspberry Pi 5
  ansible.netcommon.cli_config:
    parents: interface gigabitethernet 1/1/2
    lines:
      - description RPi5_Services
      - switchport mode access
      - switchport access vlan 50
      - spanning-tree portfast

- name: Puerto Mini PC
  ansible.netcommon.cli_config:
    parents: interface gigabitethernet 1/1/3
    lines:
      - description MiniPC_Core_Services
      - switchport mode access
      - switchport access vlan 20
      - spanning-tree portfast