---
- name: Activar IPv6 routing
  ansible.netcommon.cli_config:
    lines:
      - ipv6 unicast-routing

- name: Configurar interfaces VLAN
  ansible.netcommon.cli_config:
    parents: "interface Vlan{{ item.id }}"
    lines:
      - description "{{ item.name }}"
      - ip address {{ item.ipv4 }} {{ item.mask }}
      - ipv6 address {{ item.ipv6 }}
      - no shutdown
  loop: "{{ vlans }}"