---
- name: Incluir instalación de Bind9
  include_tasks: install.yml

- name: Incluir configuración de Bind9
  include_tasks: configure.yml

- name: Incluir creación de zonas DNS
  include_tasks: zones.yml

- name: Incluir gestión del servicio
  include_tasks: service.yml