---
# ========================================
# CONFIGURACIÓN DEL DOMINIO
# ========================================
dns_domain: "plataformas.tel"
dns_reverse_zone: "20.168.192"

# ========================================
# SERVIDOR DNS PRIMARIO (Mini PC)
# ========================================

#"192.168.20.10" -> IP Raspberry

dns_primary_ns: "ns1"
dns_primary_ip: "192.168.20.20"

# ========================================
# SERVIDORES DNS SECUNDARIOS (Raspberry Pi)
# ========================================
dns_slaves:
  - "192.168.20.1"

# ========================================
# HOSTS A REGISTRAR EN DNS (Registros A)
# ========================================
dns_hosts:
  - name: "ns1"
    ip: "192.168.20.1"
  - name: "rpi5"
    ip: "192.168.20.10"  # IP raspberry

# ========================================
# ALIAS A REGISTRAR EN DNS (Registros CNAME)
# ========================================
dns_cnames:
  - name: "ns2"
    target: "rpi5"
  - name: "kiwix"
    target: "rpi5"
  - name: "jellyfin"
    target: "rpi5"
  - name: "kolibri"
    target: "rpi5"
  - name: "squid"
    target: "rpi5"
  - name: "matrix"
    target: "rpi5"