---
# ============================================================
# Variables compartidas — RPi Biblioteca Digital Ladrilleros
# ============================================================

# Red
rpi_ip: "192.168.20.10"
minipc_captive_ip: "192.168.30.1"
minipc_captive_port: 2050
minipc_dns_ip: "192.168.10.1"

# Dominio local
dns_domain: "biblioteca.tel"

# Puertos de servicios locales (todos en loopback)
kiwix_port: 8080
kolibri_port: 8090
jellyfin_port: 8096

# Kiwix
kiwix_library: "/var/lib/biblioteca/zim/library.xml"
kiwix_user: "kiwix"

# DNS secundario
dns_primary_ip: "192.168.10.1"
dns_slave_listen_ips:
  - "127.0.0.1"
  - "192.168.20.10"
