---
- name: Deploy DNS Bind9 (biblioteca.local) en Mini PC
  hosts: minipc
  become: true
  gather_facts: true

  pre_tasks:
    - name: Actualizar cache apt
      apt:
        update_cache: true
        cache_valid_time: 3600
      tags: always

  roles:
    - role: dns
      tags: [dns]
