---
# ── Prometheus ────────────────────────────────────────────────────────────────
- name: Instalar prometheus
  apt:
    name: prometheus
    state: present
    update_cache: true
  become: true

- name: Desplegar configuración prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"
  become: true
  notify: restart prometheus

- name: Habilitar e iniciar prometheus
  systemd:
    name: prometheus
    enabled: true
    state: started
  become: true

# ── Node Exporter ─────────────────────────────────────────────────────────────
- name: Instalar node_exporter
  apt:
    name: prometheus-node-exporter
    state: present
  become: true

- name: Habilitar e iniciar node_exporter
  systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
  become: true

# ── Grafana ───────────────────────────────────────────────────────────────────
- name: Agregar repositorio GPG de Grafana
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
  become: true

- name: Agregar repositorio de Grafana
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana
  become: true

- name: Instalar grafana
  apt:
    name: grafana
    state: present
    update_cache: true
  become: true

- name: Habilitar e iniciar grafana-server
  systemd:
    name: grafana-server
    enabled: true
    state: started
  become: true
